# Use postgres/example user/password credentials
version: '3'

services:
  db:
    image: postgres
    env_file:
      .env
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - picloud

  web:
    build: .
    env_file:
      .env
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    networks:
      - picloud

  redis:
    image: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    networks:
      - picloud

networks:
  picloud:
